# Generated by Django 4.0 on 2023-12-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actividad_id_alter_avisoprivacidad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.CharField(choices=[('vend1', 'VEND1'), ('vend1', 'VEND1')], default='vend1', max_length=255, verbose_name='Vendedor'),
        ),
        migrations.CreateModel(
            name='customerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=254)),
                ('created', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
