# Generated by Django 4.0 on 2023-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_vendedor_customeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoporteServiciosFinancieros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('service_status', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SOPORTE A SERVICIOS FINANCIEROS',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo'),
        ),
    ]
