# Generated by Django 4.0 on 2023-12-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_soporteserviciosfinancieros_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ext',
            field=models.CharField(max_length=255, verbose_name='Ext.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(max_length=255, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_extra',
            field=models.CharField(max_length=255, verbose_name='Teléfono Extra'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='client',
            field=models.TextField(max_length=254),
        ),
    ]
