# Generated by Django 4.0 on 2023-12-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_ext_alter_cliente_rfc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerAddress',
            new_name='DirecciónDeReporte',
        ),
    ]
