# Generated by Django 4.0 on 2023-12-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_customeraddress_direccióndereporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='vender',
            field=models.CharField(choices=[('vendor1', 'vendor1'), ('vendor2', 'vendor2')], default=1, max_length=200, verbose_name='Vendedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sucursal',
            field=models.IntegerField(choices=[('01', '01'), ('02', '02')]),
        ),
    ]
