# Generated by Django 4.0 on 2023-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cliente_vendedor_cliente_vender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccióndereporte',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sucursal',
            field=models.IntegerField(choices=[('', '---------'), (1, 'TIJUANA'), (2, 'HERMOSILLO'), (3, 'CULIACAN'), (4, 'AGUASCALIENTES')]),
        ),
        migrations.AlterField(
            model_name='direccióndereporte',
            name='client',
            field=models.CharField(max_length=254),
        ),
    ]
