# Generated by Django 4.0 on 2023-12-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_direccióndereporte_active_alter_cliente_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='contracto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
