# Generated by Django 4.0 on 2024-01-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_three',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Correo three'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_two',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Correo two'),
        ),
        migrations.AlterField(
            model_name='direccióndereporte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
