# Generated by Django 4.0 on 2024-01-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente_email_three_cliente_email_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccióndereporte',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
