# Generated by Django 4.0 on 2024-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_direccióndereporte_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_de_cliente',
            field=models.CharField(default=1, max_length=255, verbose_name='numero'),
            preserve_default=False,
        ),
    ]
