# Generated by Django 4.0 on 2024-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_numero_de_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='contracto',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='Contrato',
            field=models.CharField(default=1, max_length=255, verbose_name='Contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_de_cliente',
            field=models.CharField(max_length=255, verbose_name='Número de Cliente'),
        ),
    ]
