# Generated by Django 4.0 on 2024-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_bitacora_contracto_bitacora_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccióndereporte',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='direccióndereporte',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
