# Generated by Django 4.0 on 2024-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_direccióndereporte_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccióndereporte',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
